In [105]:
#the code has been written with the help of the following resources
#https://github.com/AIMLC-IITD/Summer-of-ML-2021/blob/main/Week-1/Day-2/Practice-Assignment/02-insurance-linear.ipynb
# for initial code and analysing data
#https://github.com/anoopv511/COL-774-Assignments/blob/master/Assignment%201/Linear%20Regression.ipynb 
# for batch gradient descent

#Akarsh Jain
#2020CS10318
#akarshjain02@gmail.com

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

data = pd.read_csv('insurance.csv')
print(data.head())

num_rows = len(data.index)
print(num_rows)
num_cols = len(data.columns)
print(num_cols)
input_cols = list(data.columns)
print(input_cols)

print(data["charges"].describe())

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520
1338
7
['age', 'sex', 'bmi', 'children', 'smoker', 'region', 'charges']
count     1338.000000
mean     13270.422265
std      12110.011237
min       1121.873900
25%       4740.287150
50%       9382.033000
75%      16639.912515
max      63770.428010
Name: charges, dtype: float64


In [106]:
output_cols = ["charges"]
categorical_cols = list(data.select_dtypes(["object"]).columns)

for col in categorical_cols:
    data[col] = data[col].astype('category').cat.codes

x = data[input_cols].to_numpy()
x=np.delete(x,6,1)

y= data[output_cols].to_numpy()

print(np.shape(x))
print(np.shape(y))

(1338, 6)
(1338, 1)


In [107]:
x = (x - np.mean(x))/np.std(x)  #std(x)=1
print("x:",x)

aux=np.mean(y)
y=y/aux 
# value will be multiplied later so that other values do not get extremely large
# 10000 estimated from mean of the output

print("y:",y)
#testing

theta = np.zeros((x.shape[1],1))
theta_list = [theta]
diff = y - x@theta
print("diff:",diff)
print("gradient:",x.T@diff)

x: [[ 0.38988873 -0.69926733  0.90007235 -0.69926733 -0.64194332 -0.52729532]
 [ 0.33256472 -0.64194332  1.23656425 -0.64194332 -0.69926733 -0.58461932]
 [ 0.90580475 -0.64194332  1.19242477 -0.52729532 -0.69926733 -0.58461932]
 ...
 [ 0.33256472 -0.69926733  1.41312218 -0.69926733 -0.69926733 -0.58461932]
 [ 0.50453673 -0.69926733  0.77969195 -0.69926733 -0.69926733 -0.52729532]
 [ 2.79749685 -0.69926733  0.96714144 -0.69926733 -0.64194332 -0.64194332]]
y: [[1.27237277]
 [0.13002995]
 [0.33529167]
 ...
 [0.122817  ]
 [0.1513098 ]
 [2.1959633 ]]
diff: [[1.27237277]
 [0.13002995]
 [0.33529167]
 ...
 [0.122817  ]
 [0.1513098 ]
 [2.1959633 ]]
gradient: [[2365.36326143]
 [-894.86450488]
 [1500.84226512]
 [-845.90691398]
 [-897.68525834]
 [-819.84635324]]


In [108]:
def gradient_descent(x,y,eta,maxit,mincost):
    theta = np.zeros((x.shape[1],1))
    theta_list = [theta]
    diff = y - x@theta
    cost = 0.5*np.sum(diff**2)
    cost_list = [cost]
    iterations = 0
    while(cost > mincost and iterations < maxit): 
        if (iterations % 500 == 0): print(iterations," - ",cost)
        theta = theta + eta*(x.T@diff)
        theta_list.append(theta)
        diff = y - x@theta
        cost = 0.5*np.sum(diff**2)
        cost_list.append(cost)
        iterations += 1
    print(iterations," - ",cost)
    print("Final Cost - ",cost)
    print("parameters = ",theta.T)
    return theta_list, cost_list
    
theta_list, cost_list = gradient_descent(x,y,0.00002675,5000,10)

#alogrithm is clearly diverging for eta=0.000268

0  -  1225.6997408595914
500  -  487.62361190692195
1000  -  482.7186311765664
1500  -  478.5115381432655
2000  -  474.52809640909334
2500  -  470.7223911605839
3000  -  467.0800291998779
3500  -  463.58983617960916
4000  -  460.24174961202914
4500  -  457.0265833215317
5000  -  453.93593379850125
Final Cost -  453.93593379850125
parameters =  [[ 0.33697742 -0.70039125  0.54045624 -0.23893043  1.88353845 -0.93151315]]


In [109]:
#implementing a direct method of linear regression (normal equation)

alpha=np.linalg.inv(x.T@x)
beta=x.T@y
theta_new=alpha@beta
print("parameters:",theta_new.T)

#finding the cost
diff = y - x@theta_new
cost = 0.5*np.sum(diff**2)
print("cost:",cost)

#hence it can be said that the final cost after batch gradient descent is comparable to the best mathematical linear fit

parameters: [[  0.34741867 -10.63186741   0.67122089  -1.11214562  14.25094247
   -2.77771136]]
cost: 341.4717221076601
